[versions]
...
kotlin = "1.9.21" # should already be here
...
ktor = "2.3.7" # ...or latest

[libraries]
...
ktor-serializationJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }

[plugins]
...
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
