[versions]
...
koin = "3.4.0"

[libraries]
...
koin-core = {group = "io.insert-koin", name = "koin-core", version.ref = "koin"}
koin-android = {group = "io.insert-koin", name = "koin-android", version.ref = "koin"}
